"""Real-robot and reconstructed-simulation evidence contracts."""

from .artifacts import sanitized_evidence_manifest, write_real_evidence_artifacts
from .protocol import (
    REAL_EVIDENCE_LEDGER_FORMAT,
    REAL_EVIDENCE_MANIFEST,
    REAL_EVIDENCE_PACKAGE_FORMAT,
    REAL_EVIDENCE_PROTOCOL_VERSION,
    REAL_EVIDENCE_REPORT_FORMAT,
    ActionContract,
    CalibrationRecord,
    ClockContract,
    CoordinateFrame,
    EvidenceArtifact,
    GovernanceContract,
    RealEvidencePackage,
    RealRobotEpisode,
    RealSimMapping,
    ReconstructedVariant,
    SensorStream,
    TaskOutcome,
    resolve_real_evidence_manifest,
    real_evidence_conformance_fixture_path,
)
from .validation import (
    EvidenceValidationIssue,
    RealEvidenceValidationError,
    RealEvidenceValidationReport,
    RealEvidenceValidator,
    comparison_pairs,
)

__all__ = [
    "REAL_EVIDENCE_LEDGER_FORMAT",
    "REAL_EVIDENCE_MANIFEST",
    "REAL_EVIDENCE_PACKAGE_FORMAT",
    "REAL_EVIDENCE_PROTOCOL_VERSION",
    "REAL_EVIDENCE_REPORT_FORMAT",
    "ActionContract",
    "CalibrationRecord",
    "ClockContract",
    "CoordinateFrame",
    "EvidenceArtifact",
    "EvidenceValidationIssue",
    "GovernanceContract",
    "RealEvidencePackage",
    "RealEvidenceValidationError",
    "RealEvidenceValidationReport",
    "RealEvidenceValidator",
    "RealRobotEpisode",
    "RealSimMapping",
    "ReconstructedVariant",
    "SensorStream",
    "TaskOutcome",
    "comparison_pairs",
    "resolve_real_evidence_manifest",
    "real_evidence_conformance_fixture_path",
    "sanitized_evidence_manifest",
    "write_real_evidence_artifacts",
]
